### ISSUE TITLE
Outstanding Issues and Features

### ISSUE THREAD

**Issue by amadeus** [JulesWang/css.vim#30]
This is more of a general post on what I see still needs to be fixed with this repo.

I've been using it a lot recently, and things are working very well, however there are still a couple things and I wanted to get your thoughts on them.
- [ ] CSS Animation declaration support: There's an open pull request for this, however it's a bit of a hack to support. On this vein however, I do feel like even the CSS transition support is a bit of a hack, it would be nice to figure out a way to elegantly solve both of those problems.
- [x] Improve support for Pseudo selectors. We already support the simpler onces, it's the more 'functional' ones that we need to still add support for. Here's a nice rundown of them: http://css-tricks.com/pseudo-class-selectors/ It's really in the department of selectors like `:not()`, `:nth-child()` and all their related derivatives.
- [ ] Fixing broken keyword support when this syntax file is loaded with other html5 syntax plugins. Basically vendor prefixes break everything with property names that include a `-` since most html5 support plugins do `setlocal iskeyword+=-`. I think the only real solution would be to remove dependence on `keywords`, and remove the "/<some-word>/" type of syntax. This seems less than ideal, and not sure it does fully solve the problem, but it is one possibility.
- [ ] Font declarations. It's silly to try and keep every single font in here, I don't think we should error correct it. Especially now with services like Typekit, custom fonts are quite common. I think we should refactor the font and font-family declarations to properly support any font name.

**Comment by jsit** [comment]
@amadeus Can you confirm whether these remaining issues are still a problem? And if so, can you please file Issues at jsit/css.vim? Thanks.

**Comment by amadeus** [comment]
Heh, I’ve stopped using the plugin a long time ago. I use my own artisanal setup now, so I’m not really maintaining this anymore. I’ll close this issue too

**Comment by jsit** [comment]
Thanks @amadeus. Do you happen to remember the details of the remaining items? I'd love to be able to solve them if they still exist.

**Comment by amadeus** [comment]
Waay to long ago to remember, heh
