### ISSUE TITLE
Column related properties not correctly highlighted

### ISSUE THREAD

**Issue by fi5er** [JulesWang/css.vim#40]
Using Vim 7.4, several property names related to column layout are not correctly highlighted.

Test case:

```
#example1 {

    /* not correctly highlighted: */

    column-width: 1px;
    column-span: inherit;

    break-before: avoid;
    break-after: avoid;
    break-inside: avoid;

    column-break-before: avoid;
    column-break-after: avoid;
    column-break-inside: avoid;

    /* work as expected: */

    column-gap: inherit;
    column-rule-width: inherit;
    column-count: inherit;

    page-break-before: avoid;
    page-break-after: avoid;
    page-break-inside: avoid;

}
```

Screenshot: 
![css-vim-col](https://f.cloud.github.com/assets/5108568/1620445/c04569ce-5677-11e3-9bd0-875318af3b9d.png)

**Comment by amadeus** [comment]
It appears some of the values for this are not fixed, or somehow regressed, see screenshot here:

![bug](https://dl.dropboxusercontent.com/s/vmlyppx0pin9do7/test.css_2016-03-09_14-53-27.png?dl=0)
