### ISSUE TITLE
some syntax-highlight issues

### ISSUE THREAD

**Issue by mattn** [JulesWang/css.vim#53]
https://github.com/postcss/postcss/tree/master/test/cases

There are some strange syntax-highlight in css.vim

![](http://go-gyazo.appspot.com/d090494c50a46ff6.png)

**atrule-decls.css**

seems to be mis-matched `;` as end of the property value.

**escape.csss**

seems to be mis-matched `)` as end of `note()` in quoted-string.

**quotes.css**

seems to be mis-matched `\'` as end of single-quoted-string.

**Comment by JulesWang** [comment]
thanks for the bug report . I will handle it soon On 2015-04-14 14:59 , mattn Wrote: https://github.com/postcss/postcss/tree/master/test/cases There are some strange syntax-highlight in css.vim atrule-decls.css seems to be mis-matched ; as end of the property value. escape.csss seems to be mis-matched )" as end ofnote()` in quoted-string. quotes.css seems to be mis-matched \' as end of single-quoted-string. — Reply to this email directly or view it on GitHub.

**Comment by JulesWang** [comment]
atrule-decls.css
- It seems that there is no property named "famaly-name"
- There is no property 'background' in @ media, so 'background' will not be highlighted in media block.

escape.css
- Bug confirmed. 

quotes.css
- OK with following test case
a::before {
    content: ";'@ /**/\"";
    content: '\'"\\';
}

**Comment by mattn** [comment]
It seems many differences between `runtime/syntax/css.vim` and this repository. Could you please send to vim-dev or bram the latest version?

**Comment by JulesWang** [comment]
OK. Let's sync

**Comment by mattn** [comment]
Thank your fixing this. Could you please send the patch to vim-dev?

**Comment by JulesWang** [comment]
The css.vim file has been sent to Bram.

**Comment by mattn** [comment]
Thanks.
