### ISSUE TITLE
Support for "pointer-events"

### ISSUE THREAD

**Issue by tlhunter** [JulesWang/css.vim#54]
Here's some information on `pointer-events`, it's supported everywhere:

https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events

Here's the valid properties according to MDN:

```
auto, none, visiblePainted, visibleFill, visibleStroke, visible, painted, fill, stroke, all, inherit;
```

Here's properties that Chrome supports:

```
all, auto, bounding-box, fill, inherit, initial, none, painted, stroke, visible, visiblefill, visiblepainted, visiblestroke
```

**Comment by JulesWang** [comment]
Thanks for your suggestion.
By the way, the issue is closed by my commit, that's magic!
