### ISSUE TITLE
Leaking string highlight

### ISSUE THREAD

**Issue by baskerville** [JulesWang/css.vim#55]
In the following example:
```
.foo:after {
	content: "}";
}

.bar:after {
	content: "?";
}
```
The closing brace inside the first string seems to be interpreted as a true closing brace.

**Comment by fi5er** [comment]
I cannot reproduce this using Vim 7.4. The syntax highlighting looks just fine; jumping from brace to brace using % works as well.

**Comment by baskerville** [comment]
Neither can I with the Git version.

The version of *css.vim* that ships with *vim 7.4* says: *Last Change:  2013 Nov.27*.
