### ISSUE TITLE
flexbox broken, can't fix regexp myself

### ISSUE THREAD

**Issue by martensms** [JulesWang/css.vim#56]
Hey,

I tried to fix the regexp myself, but I think it's very hard to understand and I have no clue why you did these regexp in the first place.

```
syn match cssFlexibleBoxProp contained "\<box-\(align\|direction\|flex\|ordinal-group\|orient\|pack\|shadow\|sizing\)\>"
```

This regexp is broken as it doesn't match the properties properly: http://i.imgur.com/VT11FsY.png
The flex-flow and flex-pack syntax were the previous ones before justify-content was introduced.

What do I need to do in order to support all previous syntaxes?
Would it make sense to split this regexp up into the multiple variants?

**Comment by JulesWang** [comment]
Would you pls paste some test code?

**Comment by JulesWang** [comment]
Thanks for your bug report :)
