### ISSUE TITLE
Add flex highlighting support

### ISSUE THREAD

**Issue by bronzehedwick** [JulesWang/css.vim#59]
First of all, thanks for all the great work!

I'd like to add flexbox module syntax highlighting. Currently terms look like this:

![screen shot 2016-02-25 at 2 20 14 pm](https://cloud.githubusercontent.com/assets/637174/13331363/1faac41a-dbcb-11e5-8ea8-5e11f5516d69.png)

Still wrapping my head around vimscript, but I can make a PR for this if the idea is accepted.

**Comment by JulesWang** [comment]
No problem, I will check and patch it. Besides, flex is a great tool for css layout :)

**Comment by JulesWang** [comment]
AFAK, flex box syntax highlighting is supported, pls check whether you have the latest version of css.vim

**Comment by JulesWang** [comment]
I have fixed a bug in line1 display: flex; 
Other lines are ok with latest version.

**Comment by bronzehedwick** [comment]
Ah, I was relying on the version shipped in vim. Updated and now the flex highlighting works. Thanks!
