### ISSUE TITLE
Does not higlight max-content

### ISSUE THREAD

**Issue by SIGSTACKFAULT** [JulesWang/css.vim#63]
`max-content`, a property for things like `width` and `height`, isn't a keyword.

Default color scheme:
![Default](https://cloud.githubusercontent.com/assets/14184826/24713289/364ac08c-19f3-11e7-8869-d133d39e3220.PNG)

'Desert' color scheme, just to be sure:
![Desert](https://cloud.githubusercontent.com/assets/14184826/24713252/1c44642c-19f3-11e7-8e3f-1fc51de13569.PNG)

**Comment by JulesWang** [comment]
According to this [document](https://drafts.csswg.org/css-sizing-3/#width-height-keywords)

'max-content' is still a working draft. Better add these new keywords when the draft becoming a recommendation. :-)

**Comment by Blacksilver42** [comment]
At some point I'll make a fork with those changes...

As soon as I learn how to write vim syntax files.

**Comment by jsit** [comment]
Still in "working draft," new link:

https://www.w3.org/TR/css-sizing-3/
