### ISSUE TITLE
Official Vim Syntax for CSS?

### ISSUE THREAD

**Issue by rwhorman** [JulesWang/css.vim#64]
In the latest Vim v8 distribution, I see that the bundled `css.vim` is ostensibly from this repo:

```
 " Language:     Cascading Style Sheets
 " Previous Contributor List:
 "               Claudio Fleiner <claudio@fleiner.com> (Maintainer)
 "               Yeti            (Add full CSS2, HTML4 support)
 "               Nikolai Weibull (Add CSS2 support)
 " Maintainer:   Jules Wang      <w.jq0722@gmail.com>
 " URL:          https://github.com/JulesWang/css.vim
 " Last Change:  2017 Jan 14
 "               cssClassName updated by Ryuichi Hayashida Jan 2016
```

However, the version bundled with Vim and the latest version in this repo do not match. In fact, the `Last Change` called out in the Vim-bundled file is Jan of this year:

```
" Last Change:  2017 Jan 14
```

Which does not appear to have come from this repo as the last change here was Mar 2016. 

A quick diff shows the latest commit here in this repo is quite a bit diff from latest in the Vim distribution.

I am asking because I found a few issues with the syntax highlighting with the Vim-bundled `css.vim` and would like to know where to fix it 😉 .

So wondering if this the repo of the official `css.vim`?  If so, is it just a matter of the Vim distribution getting an update from this repo?  

Thx for your help to sort this out!

**Comment by JulesWang** [comment]
Thanks for telling me that finally VIM has come to github, which I should have noticed long before....

That meaning I could maintain css.vim in github by PR.

So I will make this repo deprecated.

I would like to know your issues and maybe I could give you a hand  :-)

**Comment by rwhorman** [comment]
For reference, here is the issue in the `vim` repo where this will be addressed:

https://github.com/vim/vim/issues/1705

**Comment by JulesWang** [comment]
@enigmata  For you information, I use this repo again as Bram prefer a whole file to a patch/PR.

**Comment by Strangehill** [comment]
I'd like to see proper highlighting too and I too have an outdated file. :/ Has this been merged?

**Comment by JulesWang** [comment]
@Strangehill  Yes,  pls check  https://github.com/vim/vim/blob/master/runtime/syntax/css.vim
