### ISSUE TITLE
highlight | display: flow-root 

### ISSUE THREAD

**Issue by dagolinuxoid** [JulesWang/css.vim#66]
Hi there. Take it into consideration.
[![highligh_style_vim.png](https://s19.postimg.cc/drmauttc3/highligh_style_vim.png)](https://postimg.cc/image/lkcymszb3/)

**Comment by dsifford** [comment]
@JulesWang What is the cost of adding working draft items to the syntax? Why does that even matter?

I get that if they don't end up making it to the spec, they'd have to be pruned out, but why not just keep a section in the syntax for these draft items and them update them at some regular interval? This can even be scripted to happen automatically.

It drives me sort of nuts to see all of these things not receiving highlighting when most of us are using them already.... Here's a small list of some of the broken items I can see in a file I have open right now..

```
display: flex
display: grid
calc()
flex-start
flex-end
min-content
fit-content()
vh (units)
vw (units)
% (units)
fr (units)
```

And this is just from **one** file I have open....

**Comment by JulesWang** [comment]
> I get that if they don't end up making it to the spec, they'd have to be pruned out, but why not just keep a section in the syntax for these draft items and them update them at some regular interval? This can even be scripted to happen automatically.

Yes, that's a prefect solution to this problem. Both regular checking and script writing cost time. As a part time maintainer I use my limited time to make this file stable.  Welcome to give me a hand. :-)

>It drives me sort of nuts to see all of these things not receiving highlighting when most of us are using them already.... Here's a small list of some of the broken items I can see in a file I have open right now..

pls download the latest css.vim in this repo to  confirm your problem. Many of them are highlighted.

And PLS create a new issue to report the items which are not highlighted.

**Comment by dsifford** [comment]
@JulesWang Happy to help maintain if you need a hand.

> pls download the latest css.vim in this repo to confirm your problem. Many of them are highlighted.

What is the interval that these syntaxes make it into vim core? Is there a regular release cycle or? What about with neovim? Same?

**Comment by JulesWang** [comment]
> What is the interval that these syntaxes make it into vim core? Is there a regular release cycle or? What about with neovim? Same?

I follow Bram's instructions: Email a copy of css.vim to Bram when I *feel* this file ought to be updated. I know this is a outdated or bad software developing process. But this is what happens.

I have no idea about neovim.

Happy hacking css.vim.
