### ISSUE TITLE
set `cssPositioningAttr` will effect position property's frontend color

### ISSUE THREAD

**Issue by willnew** [JulesWang/css.vim#67]
I set `cssPositioningProp` yellow and `cssPositioningAttr` red in my theme plugin, what I expected is the `cssPositioningProp` all have yellow frontend color, but this is what I get:
![1529459024267](https://user-images.githubusercontent.com/1535543/41632842-73316894-746e-11e8-9421-542d07c756d0.jpg)

Then I change frontend color of `cssPositioningAttr` into green, the result is:
![1529459107242](https://user-images.githubusercontent.com/1535543/41632879-a44f8e56-746e-11e8-8837-417668fe5dc9.jpg)

I ignored `cssPositioningAttr` at the last time, `rigtht` and `left` are not colored then.
It seems `cssPositioningProp` doesn't control all properties as we want and `cssPositioningAttr` effects some properties, I noticed the syntax in css.vim, and seems this part makes the overwritten, but why doesn't it work if I only set `cssPositioningProp`?

`syn keyword cssPositioningProp contained bottom clear clip display float left`
`syn keyword cssPositioningProp contained position right top visibility`
`...`
`syn keyword cssPositioningAttr contained left right both`

**Comment by JulesWang** [comment]
Maybe you need to set `cssAttrRegion`  

https://github.com/JulesWang/css.vim/blob/master/syntax/css.vim#L473


We can talk in Chinese if you want. :-)

**Comment by willnew** [comment]
哈哈，let's do it. 我刚才在怀疑是因为我安装的[另外一个syntax plugin](https://github.com/groenewege/vim-less)的影响，然后我尝试把它删除了过后确实样式和我预期的一样了，看来是因为那个插件的规则对css.vim的规则有一定的影响，我还是先把这个issue关了去看一下vim-less的代码吧。谢谢 ;)
