### ISSUE TITLE
Pseudo-Element Selectors Inside a Media Query and "display: unset"

### ISSUE THREAD

**Issue by JamesGreenaway** [JulesWang/css.vim#69]
![image](https://user-images.githubusercontent.com/16066511/46970035-ce12e880-d0af-11e8-8a2f-5f67530202f8.png)

Closing bracket for the media query seems to be thrown off by the colon for the pseudo-element.  
&& 
"unset" is not reconised when used in conjuction with the display property (this is not affected by the media query).

**Comment by JulesWang** [comment]
Thanks for reporting these issues. The second issue will be fixed by pr #70

The first issue is much more tricky. It will be fixed in a few days or more.
