### ISSUE TITLE
Keywords and matches are highlighted even out of context

### ISSUE THREAD

**Issue by jsit** [JulesWang/css.vim#73]
Try the following valid CSS:

```css
:root {
  --small-height: 100px;
}

div {
  height: var(--small-height);
}
```

Here is the highlighting I see:

<img width="283" alt="Screen Shot 2019-07-23 at 1 32 26 PM" src="https://user-images.githubusercontent.com/643417/61733692-54024500-ad4e-11e9-959c-31b989285c7d.png">

The first `--small` is being recognized as a `cssTagName`, due to this line:

```vim
syn keyword cssTagName option p param pre q s samp script small
```

The second `--small` is being recognized as a `cssFontAttr`, due to this line:

```vim
syn match cssFontAttr contained "\<\(x\{1,2\}-\)\=\(large\|small\)\>"
```

These `keyword` and `match` lines are far too general; `small` is only a `cssTagName` when it is used in a selector; and it is only a `cssFontAttr` when it is used as the value of a definition.

The example used here uses custom properties, but words like this could occur in other places as well, especially in SCSS files, which inherit CSS syntax highlighting definitions.

In any case it seems overzealous to assume that all instances of `small` will refer to font size or tag names.

**Comment by JulesWang** [comment]
css variables, I see...  
Thanks for remind me that,  plenty work to do. :-)

**Comment by jsit** [comment]
I wonder if it would be wise to create a `region` for CSS property values -- anything after a property and between a colon and a semicolon, basically -- and make these keywords `containedin` that region?

**Comment by JulesWang** [comment]
It seems impossible to escape keyword match in the following examples.
```css
div {
   color: black;
}
div {
   --color: black;
}
```
Or replace all the keyword matches? That's crazy...

**Comment by JulesWang** [comment]
It turns out simple than I thought, thanks vary much for remind me this issue. 
Would you pls help me test this commit and I will send this file to Bram in a few days if everything is ok.

**Comment by JulesWang** [comment]
The css.vim file have been sent to Bram.
