### ISSUE TITLE
Detect at-rules

### ISSUE THREAD

**Issue by albfan** [JulesWang/css.vim#82]
Parsing this file: https://gitlab.gnome.org/GNOME/gitg/-/blob/master/gitg/resources/ui/style.css#L1

this at rules are not correctly identified (colors show as `cssIdentifier` when starts by #letter):

```
@define-color butter1 #fce94f;
@define-color butter2 #edd400;
@define-color butter3 #c4a000;

@define-color orange1 #fcaf3e;
@define-color orange2 #f57900;
@define-color orange3 #ce5c00;

@define-color chocolate1 #e9b96e;
@define-color chocolate2 #c17d11;
@define-color chocolate3 #8f5902;
```

In this format, colors are recognized as `cssDefinition`:

```
@define-color {
	butter1 #fce94f;
	butter2 #edd400;
	butter3 #c4a000;

	orange1 #fcaf3e;
	orange2 #f57900;
	orange3 #ce5c00;

	chocolate1 #e9b96e;
	chocolate2 #c17d11;
	chocolate3 #8f5902;
```

The plan is to modify the file to use the second format, but looks like this syntax is uncovered by css.

**Comment by JulesWang** [comment]
Interesting feature. This repo is deprecated. please jump to https://github.com/jsit/css.vim    @jsit

**Comment by jsit** [comment]
@albfan Feel free to open an issue on my repo, but this doesn't look like standard CSS, so I don't know that it would make sense to support it.

**Comment by albfan** [comment]
@jsit not an css expert. if it is not standard then is just some gtk customization, and just move to standard is a better idea.
